<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import type { UiProps } from '../types'

const { t } = useI18n()
const props = defineProps<UiProps>()
const state = props.state
const actions = props.actions
</script>

<template>
<div v-if="state.showProfileForm" class="modal-shade" @click.self="state.showProfileForm = false"><form class="modal-panel wide-modal" @submit.prevent="actions.saveProfile"><div class="modal-head"><h2>{{ t(state.editingProfileId ? 'nodes.editNode' : 'nodes.addNode') }}</h2><button class="tool-button" type="button" @click="state.showProfileForm = false">×</button></div><div class="form-grid three-col"><label>{{ t('nodes.type') }}<select v-model="state.profileForm.configType"><option v-for="kind in state.protocolTypes" :key="kind">{{ kind }}</option><option value="PolicyGroup">PolicyGroup</option><option value="ProxyChain">ProxyChain</option></select></label><label>{{ t('nodes.coreType') }}<select v-model="state.profileForm.coreType"><option v-for="core in state.coreTypes" :key="core">{{ core }}</option></select></label><label>{{ t('nodes.remarks') }}<input v-model="state.profileForm.remarks" required /></label><label>{{ t('nodes.address') }}<input v-model="state.profileForm.address" /></label><label>{{ t('nodes.port') }}<input v-model.number="state.profileForm.port" type="number" min="0" max="65535" /></label><label>{{ t('nodes.network') }}<input v-model="state.profileForm.network" /></label><label>{{ t('nodes.password') }}<input v-model="state.profileForm.password" /></label><label>{{ t('nodes.username') }}<input v-model="state.profileForm.username" /></label><label>{{ t('nodes.streamSecurity') }}<input v-model="state.profileForm.streamSecurity" /></label><label>{{ t('nodes.sni') }}<input v-model="state.profileForm.sni" /></label><label>{{ t('nodes.tls') }}<input v-model="state.profileForm.alpn" /></label><label>{{ t('nodes.fingerprint') }}<input v-model="state.profileForm.fingerprint" /></label><label>{{ t('nodes.publicKey') }}<input v-model="state.profileForm.publicKey" /></label><label>{{ t('nodes.shortId') }}<input v-model="state.profileForm.shortId" /></label><label class="check-inline"><input v-model="state.profileForm.allowInsecure" type="checkbox" />{{ t('nodes.allowInsecure') }}</label></div><div class="form-grid two-col extra-json-grid"><label>{{ t('nodes.protoExtra') }}<textarea v-model="state.profileForm.protoExtraText" class="code-area" spellcheck="false"></textarea></label><label>{{ t('nodes.transportExtra') }}<textarea v-model="state.profileForm.transportExtraText" class="code-area" spellcheck="false"></textarea></label></div><label class="advanced-profile-label">{{ t('nodes.advancedProfileFields') }}<textarea v-model="state.profileAdvancedJson" class="code-area advanced-profile-json" spellcheck="false"></textarea></label><p v-if="state.profileModalError" class="inline-error">{{ state.profileModalError }}</p><div class="modal-actions"><button class="button" type="button" @click="state.showProfileForm = false">{{ t('common.cancel') }}</button><button class="button primary" type="submit">{{ t('common.save') }}</button></div></form></div>
</template>
