<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import type { UiProps } from '../types'

const { t } = useI18n()
const props = defineProps<UiProps>()
const state = props.state
const actions = props.actions
</script>

<template>
<div v-if="state.showSubscriptionForm" class="modal-shade" @click.self="state.showSubscriptionForm = false"><form class="modal-panel wide-modal" @submit.prevent="actions.saveSubscription"><div class="modal-head"><h2>{{ t(state.editingSubscriptionId ? 'subscriptions.editSubscription' : 'subscriptions.addSubscription') }}</h2><button class="tool-button" type="button" @click="state.showSubscriptionForm = false">×</button></div><div class="form-grid two-col"><label>{{ t('subscriptions.name') }}<input v-model="state.subscriptionForm.remarks" required /></label><label>{{ t('subscriptions.url') }}<input v-model="state.subscriptionForm.url" required /></label><label>{{ t('subscriptions.moreUrl') }}<input v-model="state.subscriptionForm.moreUrl" /></label><label>{{ t('subscriptions.interval') }}<input v-model.number="state.subscriptionForm.autoUpdateInterval" type="number" min="0" /></label><label>{{ t('subscriptions.userAgent') }}<input v-model="state.subscriptionForm.userAgent" /></label><label>{{ t('subscriptions.convertTarget') }}<input v-model="state.subscriptionForm.convertTarget" /></label><label>{{ t('subscriptions.filter') }}<input v-model="state.subscriptionForm.filter" /></label><label>{{ t('subscriptions.sort') }}<input v-model.number="state.subscriptionForm.sort" type="number" /></label><label>{{ t('subscriptions.prevProfile') }}<input v-model="state.subscriptionForm.prevProfile" /></label><label>{{ t('subscriptions.nextProfile') }}<input v-model="state.subscriptionForm.nextProfile" /></label><label>{{ t('subscriptions.preSocksPort') }}<input v-model.number="state.subscriptionForm.preSocksPort" type="number" /></label><label>{{ t('subscriptions.customCoreType') }}<select v-model="state.subscriptionForm.customCoreType"><option :value="null">{{ t('common.none') }}</option><option v-for="core in state.coreTypes" :key="core" :value="core">{{ core }}</option></select></label><label class="wide-field">{{ t('subscriptions.requestHeaders') }}<textarea v-model="state.subscriptionForm.requestHeaders"></textarea></label><label class="wide-field">{{ t('subscriptions.memo') }}<textarea v-model="state.subscriptionForm.memo"></textarea></label><label class="check-inline"><input v-model="state.subscriptionForm.enabled" type="checkbox" />{{ t('subscriptions.enabled') }}</label></div><div class="modal-actions"><button class="button" type="button" @click="state.showSubscriptionForm = false">{{ t('common.cancel') }}</button><button class="button primary" type="submit">{{ t('common.save') }}</button></div></form></div>
</template>
